---
title: "p8105_hw6_rz2570"
author: "Ruilian Zhang"
date: "11/25/2021"
output: github_document
---

```{r}
library(tidyverse)

theme_set(theme_minimal() + theme(legend.position = "bottom"))
```


## Problem 1

```{r import data}
birth_df = read_csv("data/birthweight.csv") %>% 
  mutate(
    babysex = factor(babysex),
    frace = factor(frace),
    malform = factor(malform),
    mrace = factor(mrace)
    )

 
birth_df %>% 
  summarize_all(~ sum(is.na(.))) %>% 
  knitr::kable()
```

* Convert some numeric data to factor for regression analysis.  
* The table above shows that there are no missing values in the data.  

```{r regression model}
fit = lm(bwt ~ blength, data = birth_df) 

fit %>% 
  broom::tidy() %>% 
  knitr::kable(digits = 3)

birth_df %>% 
  select(bwt, blength) %>% 
  modelr::add_residuals(fit) %>% 
  modelr::add_predictions(fit) %>% 
  ggplot(aes(x = resid, y = pred)) +
  geom_point()
```

```{r compare models}
fit1 = lm(bwt ~ blength + gaweeks, data = birth_df)

fit1 %>% 
  broom::tidy() %>% 
  knitr::kable(digits = 3)

fit2 = lm(bwt ~ bhead + blength + babysex + bhead*blength + bhead*babysex + blength*babysex + bhead*blength*babysex, data = birth_df)

fit2 %>% 
  broom::tidy() %>% 
  knitr::kable(digits = 3)
```

 
## Problem 2

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

